<script setup lang="ts">
import { iconRegistry, isIconRegistered } from '@/icon-registry';
import { computed, type Component } from 'vue';
import IconHelpCircle from '~icons/lucide/help-circle';

const props = defineProps<{ icon?: string | null }>();

// NavigationIcon - Resolves icons from backend navigation data
//
// This component uses an auto-generated icon registry that scans
// PHP files for icon references. The registry is rebuilt automatically
// when icon usage changes in PHP files.
//
// Icons are mapped from backend strings (e.g., 'lucide:settings')
// to Vue components using the generated registry located at
// resources/js/icon-registry.ts (imported via @vite alias).
//
// The registry is generated by the icon-registry-generator Vite plugin
// which scans all PHP files in app and modules directories.
//
// Fallback: If an icon is not found, displays a help-circle icon
// and shows a warning in development mode.

const iconComponent = computed<Component | null>(() => {
    if (!props.icon) return null;

    // Check registry for icon
    if (isIconRegistered(props.icon)) {
        return iconRegistry[props.icon];
    }

    // Fallback handling
    if (import.meta.env.DEV) {
        console.warn(
            `[NavigationIcon] Icon not registered: "${props.icon}"\n` +
                `The icon registry is auto-generated from PHP files.\n` +
                `Make sure your icon is defined in a PHP file with:\n` +
                `'icon' => '${props.icon}'`,
        );
    }

    // Return fallback icon instead of null
    return IconHelpCircle;
});
</script>

<template>
    <component :is="iconComponent" v-if="iconComponent" />
</template>
