/**
 * Template generator for icon registry TypeScript file
 */

/**
 * Generate the icon registry TypeScript code
 *
 * @param {Array} parsedIcons - Array of parsed icon objects with { identifier, library, name, importPath, importName }
 * @returns {string} TypeScript code for the icon registry
 */
export function generateIconRegistryTemplate(parsedIcons) {
    const timestamp = new Date().toISOString();

    // Generate import statements
    const imports = parsedIcons
        .map((icon) => `import ${icon.importName} from '${icon.importPath}';`)
        .join('\n');

    // Generate registry mappings
    const mappings = parsedIcons
        .map((icon) => `  '${icon.identifier}': ${icon.importName},`)
        .join('\n');

    return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by icon-registry-generator Vite plugin
 * Last updated: ${timestamp}
 *
 * This file is automatically generated by scanning PHP files
 * for icon references. Changes to this file will be overwritten.
 */

import type { Component } from 'vue';

// Icon imports (alphabetically sorted by library, then name)
${imports}

/**
 * Icon registry mapping icon identifiers to Vue components
 * Format: 'library:icon-name' => IconComponent
 */
export const iconRegistry: Record<string, Component> = {
${mappings}
};

/**
 * List of all registered icon identifiers
 */
export const registeredIcons = Object.keys(iconRegistry);

/**
 * Check if an icon is registered
 */
export function isIconRegistered(icon: string): boolean {
  return icon in iconRegistry;
}
`;
}
